### ISSUE TITLE
Input from camera looks fine, but the output from Mercator's Studio flickers 

### ISSUE THREAD

**Issue by jesuslencina** [FlyOrBoom/mercator#10] opened 2021-01-23 17:54 UTC
In Google Chrome, the extension works like a charm, and it's really useful to make the scene much brighter and vivid. However, in Microsoft Edge (using Chromium's engine), the output from mercator studio flickers and tears for some reason, but the input shown on the left (directly from the camera) is alright. Any ideas on how I could fix this? 

Thanks!

**Comment by xingyzt** [comment] 2021-03-12 19:44
I think the flickering is due to Google Meet sampling the output as Mercator is applying effects to it. If that is the cause, then it should be fixed by the latest update, 1.17.0, which should be published on the web store soon.

**Closed as completed by xingyzt** 2021-03-12 19:44 UTC
